/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/player_stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_player_stats_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/player_stats/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_player_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_tournaments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tournaments/{tournament_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_tournament"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GameDetail: {
            /** Format: int32 */
            game_id: number;
            players: components["schemas"]["PlayerGameResult"][];
            session_name: string;
            /** Format: date */
            tournament_date: string;
            /** Format: int32 */
            tournament_id: number;
            tournament_location: string;
            tournament_name: string;
            tournament_sub_name: string;
        };
        GameInfo: {
            /** Format: int32 */
            forfeit_game_point: number;
            /** Format: int32 */
            id: number;
            player_results: components["schemas"]["PlayerGameResult"][];
        };
        PlayerGameResult: {
            /** Format: int32 */
            game_point: number;
            /** Format: float */
            place_point: number;
            /** Format: int32 */
            player_id: number;
            player_name: string;
            /** Format: float */
            table_point: number;
        };
        PlayerStats: {
            /** Format: float */
            avg_gp?: number | null;
            /** Format: float */
            avg_pp?: number | null;
            /** Format: float */
            avg_tp?: number | null;
            /** Format: int64 */
            first_place_count?: number | null;
            /** Format: float */
            first_place_ratio?: number | null;
            /** Format: int64 */
            fourth_place_count?: number | null;
            /** Format: float */
            fourth_place_ratio?: number | null;
            /** Format: int64 */
            game_count?: number | null;
            /** Format: int32 */
            player_id: number;
            player_name: string;
            /** Format: int64 */
            second_place_count?: number | null;
            /** Format: float */
            second_place_ratio?: number | null;
            /** Format: int64 */
            third_place_count?: number | null;
            /** Format: float */
            third_place_ratio?: number | null;
            /** Format: int64 */
            total_gp?: number | null;
            /** Format: float */
            total_pp?: number | null;
            /** Format: float */
            total_tp?: number | null;
        };
        PlayerStatsWithGames: {
            /** Format: float */
            avg_gp?: number | null;
            /** Format: float */
            avg_pp?: number | null;
            /** Format: float */
            avg_tp?: number | null;
            /** Format: int64 */
            first_place_count?: number | null;
            /** Format: float */
            first_place_ratio?: number | null;
            /** Format: int64 */
            fourth_place_count?: number | null;
            /** Format: float */
            fourth_place_ratio?: number | null;
            /** Format: int64 */
            game_count?: number | null;
            /** Format: int32 */
            player_id: number;
            player_name: string;
            /** Format: int64 */
            second_place_count?: number | null;
            /** Format: float */
            second_place_ratio?: number | null;
            /** Format: int64 */
            third_place_count?: number | null;
            /** Format: float */
            third_place_ratio?: number | null;
            /** Format: int64 */
            total_gp?: number | null;
            /** Format: float */
            total_pp?: number | null;
            /** Format: float */
            total_tp?: number | null;
        } & {
            game_details: components["schemas"]["GameDetail"][];
        };
        RoundPoint: {
            /** Format: int32 */
            game_point: number;
            /** Format: float */
            table_point: number;
        };
        SessionDetail: {
            games: components["schemas"]["GameInfo"][];
            info: components["schemas"]["SessionInfo"];
        };
        SessionInfo: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        TotalPoint: {
            /** Format: int32 */
            game_point: number;
            /** Format: float */
            table_point: number;
        };
        Tournament: {
            /** Format: date */
            date: string;
            /** Format: int32 */
            id: number;
            location: string;
            name: string;
            sub_name: string;
        };
        TournamentDetail: {
            /** Format: int32 */
            id: number;
            info: components["schemas"]["Tournament"];
            sessions: components["schemas"]["SessionDetail"][];
            summary: components["schemas"]["TournamentSummary"][];
        };
        TournamentSummary: {
            /** Format: int32 */
            player_id: number;
            player_name: string;
            round_point: components["schemas"]["RoundPoint"][];
            total_point: components["schemas"]["TotalPoint"];
            /** Format: int32 */
            tournament_place: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_player_stats_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 玩家统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStats"][];
                };
            };
        };
    };
    get_player_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 玩家ID */
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 玩家统计和比赛详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatsWithGames"];
                };
            };
            /** @description 玩家未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_tournaments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament list with details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentDetail"][];
                };
            };
        };
    };
    get_tournament: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tournament ID */
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentDetail"];
                };
            };
            /** @description Tournament not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
